README.md, pynitrokey/cli/program.py, pynitrokey/cli/update.py, pynitrokey/helpers.py, pynitrokey/start/upgrade_by_passwd.py
fixes #21 
* straight forward FIDO2 update 
* updated README.md
=> activate automatic update for the NK FIDO2

pynitrokey/cli/fido2.py, pynitrokey/fido2/operations.py
Handy for:
- https://github.com/Nitrokey/nitrokey-fido2-firmware/pull/68
- https://github.com/Nitrokey/nitrokey-fido2-firmware/issues/67
=> Allow to specify pages count for Nitrokey FIDO2 firmware merge

pynitrokey/cli/nk3/test.py
This print statement was added by accident.
=> nk3: Remove unnecessary print statement

pynitrokey/cli/nk3/__init__.py, pynitrokey/nk3/bootloader.py
This patch adds the validate-update command that can be used to manually
validate a firmware image that has been downloaded from Github manually
or using the fetch-update command.
Fixes https://github.com/Nitrokey/pynitrokey/issues/137
=> nk3: Add validate-update command

pynitrokey/cli/nk3/__init__.py, pynitrokey/helpers.py, pynitrokey/nk3/updates.py, pynitrokey/updates.py
This PR tries to make the update command a bit easier to read by introducing new helpers.  I wanted to add most of these helpers when I originally wrote the code but did not have the time to actually write them.
=> nk3: Cleanup update command

pynitrokey/cli/storage.py, pynitrokey/helpers.py, pynitrokey/libnk.py
Hi!
This PR adds support for (un)locking the main encrypted volume, (un)locking and creating hidden volumes.
=> Add support for Nitrokey Storage

pynitrokey/cli/_patches.py, pynitrokey/cli/fido2.py, pynitrokey/cli/pro.py, pynitrokey/cli/program.py, pynitrokey/cli/update.py, pynitrokey/fido2/__init__.py, pynitrokey/fido2/client.py, pynitrokey/helpers.py, pynitrokey/libnk.py, pynitrokey/start/rsa.py, pynitrokey/start/threaded_log.py, pynitrokey/start/upgrade_by_passwd.py
This patch fixes some of the flake8 and mypy issues in the existing codebase, namely:
- unused imports
- unnecessary f-strings without placeholders
- a missing type annotation
=> Fix some flake8 and mypy issues

docs/developer-guide.rst
This patch adds instructions on setting up the environment to the
developer guide.
=> Document environment setup in developer guide

pynitrokey/nk3/device.py
=> nk3: convert hid path from str to bytes for windows systems

pynitrokey/cli/nk3/__init__.py, pynitrokey/cli/nk3/update.py, pynitrokey/nk3/updates.py
This PR adds more flexibility and visualization for the final step of an update (wait for the device to appear).
* Based on variant, old version and new version additional (to be confirmed) information may be provided for the user for specific upgrade paths so e.g., a migration can be clearly labeled.
* Added "finalization" stage for the update process, which basically translates to the waiting timeout for the device to re-appear. These timeouts may also be update-path specific
* Extend `UpdateUI` with `finalization_progress_bar` to visualize the timeout to wait until the device re-appears
* Increase the default wait timeout for all devices to 15secs
- OS: Arch
- device's firmware version: 1.2.2
Fixes #324
=> nk3: variable update timeouts & information

.flake8, .github/pull_request_template.md, .github/workflows/ci.yaml, Makefile, docs/developer-guide.rst, pyproject.toml
This PR adds a CI pipeline to run checks on pushes to non-master branches and pull request.
- Adds a Github workflow file.
- Restructures check and fix targets in the Makefile.
- Moves check configuration to `.flake8` or `pyproject.toml` configuration files.
- Changes pull request template to reflect the change in the process.
- OS:
Fixes #
=> CI pipeline for checks on PR creation and branch pushes

pynitrokey/helpers.py
Fixes: https://github.com/Nitrokey/pynitrokey/issues/345
- device's model: NK FIDO 2
=> Remove duplicate prompt in AskUser

pynitrokey/test_secrets_app.py
This PR updates tests for Secrets App
- Allow to create multiple prefixed credentials after the same test multiple passes (useful for quick light load tests)
- Disable version check in the YK low level test
- OS: Linux Fedora 38
- device's model: USB/IP Sim for Secrets App
- device's firmware version: Secrets App 0.11.0-12-gd1b083dc
=> Update tests for the Secrets App

Makefile
adding test reporting to be used inside the HIL
=> Add test reports

pynitrokey/cli/nethsm.py
This PR prints the value of type and mechanism for NetHSM `get_key` function.
-
- OS:
Fixes #
=> Display value for type and mechanism on NetHSM get_key

MAINTAINERS.md
Fixes: https://github.com/Nitrokey/pynitrokey/issues/516
=> Add Sosthène to maintainers file

pyproject.toml
Fixes: https://github.com/Nitrokey/pynitrokey/issues/528
=> Support spsdk 2.1

pynitrokey/cli/nk3/piv.py
This PR updates the prompts shown in the subcommand change-pin of the piv subcommand to allow for a better user experience.
- Update prompt texts in the click options.
- OS: macOS Sequoia 15.0
- device's model: Nitrokey 3C NFC
- device's firmware version: `v1.7.2-test.20240813`
=> Update prompt to more meaningful texts

pynitrokey/cli/fido2.py, pynitrokey/cli/trussed/tests.py
This PR updates the `nk3 test`, `fido2 make-credential` and `fido2 verify` commands to verify the attestation signature returned by the device after calling the makeCredential operation.  Previously, we only checked the attestation certificate.
=> Check attestation signature after FIDO2 makeCredential

pynitrokey/cli/nk3/piv.py
This PR adds the serial number and issuer of the certificates to the `list-certificates` command.
=> PIV certificate list properties

pynitrokey/cli/fido2.py
Fixes: https://github.com/Nitrokey/pynitrokey/issues/503
=> fido2 reset: Improve wording
