README.md
nitropy.py
win_setup.py

* adds `win_setup.py` (cx_freeze config) and `nitropy.py` (needed entrypoint for cx_freeze)
* one can build the MSI installer by just running `python win_setup.py bdist_msi` (only windows obviously)
* the resulting MSI will install nitropy globally and set the paths accordingly to allow `nitropy` being called from `cmd`
* how to update the FIDO2 under windows is documented inside the `README.md`
I would suggest bumping the version with this (+ #25) to 0.3.3, publish it to pypi and provide the `.msi` within releases

MSI Installer + Instructions for Windows

---

pynitrokey/cli/__init__.py

This patch series removes the highlighting from the banner message and prints it to stderr instead of stdout.

Update banner message

---

pynitrokey/cli/__init__.py
pynitrokey/cli/update.py
pynitrokey/helpers.py

This PR moves all initialization code (that I’ve found) into the `nitropy` function in the `pynitrokey.cli` module and configures the logger to only create log files if there are log messages, as discussed in #68.

Refactor initialization code

---

README.md

This patch adds a paragraph to the readme that explains that we need the
udev rules and how to install them.

Describe udev rule installation in readme

---

Makefile

Previosuly, the CI task system-pip-install-last-version tried to
determine the latest package version by grepping the output of pip.
This did not work properly and caused build failures.  With this patch,
we use the $VERSION variable instead (which is read from the
pynitrokey/VERSION) file.  Fixes #15.

Use VERSION file in CI

---

pynitrokey/helpers.py

This patch adds a missing LOG_FN import to pynitrokey/helpers.py that
was mistakenly removed in 2bafd3573ff7d31db6888eea9c464dd7f69792df.

Add missing LOG_FN import to helpers

---

pynitrokey/cli/fido2.py
pynitrokey/fido2/client.py

Restore returning certificate, as it was before the d885ba7fa160e725e080fcffbc75632378950a9f change,
but with an optional parameter to not break the current implementation.
Fixes #96

Correct fido2 verify command

---

Makefile
mypy.ini
pynitrokey/cli/__init__.py
pynitrokey/cli/nk3.py
pynitrokey/nk3/__init__.py
pynitrokey/nk3/base.py
pynitrokey/nk3/device.py

This patch adds the nk3 subcommand that can be used to list and query
Nitrokey 3 devices.  Note that the wink command does not yet work with
firmware version 1.0.0.

Add basic support for managing Nitrokey 3 devices

---

ci-requirements.txt
pynitrokey/fido2/client.py
pyproject.toml

The fido2 library added the serial number to the device descriptor in
version 0.9.3, so we have to bump this dependency for the --serial
option to work reliably.  This patch also fixes the find_device method
to properly query the serial number.  (The descriptor is a named tuple,
not a dictionary.)
Fixes #101.

fido2: Fix serial number selection

---

Makefile
mypy.ini
pynitrokey/fido2/client.py
pynitrokey/stubs/fido2/__init__.pyi
pynitrokey/stubs/fido2/attestation.pyi
pynitrokey/stubs/fido2/client.pyi
pynitrokey/stubs/fido2/ctap.pyi
pynitrokey/stubs/fido2/ctap1.pyi
pynitrokey/stubs/fido2/ctap2.pyi
pynitrokey/stubs/fido2/hid/__init__.pyi
pynitrokey/stubs/fido2/hid/base.pyi

This patch adds stubs for the fido2 library that are used by mypy for
the static type analysis.  This is necessary as fido2 does not have type
annotations and is not part of the typeshed repository.  Our type stubs
only contain definitions for the functions that are used in typed code
and are by no means complete.

Add type stubs for fido2

---

ci-requirements.txt
mypy.ini
pyproject.toml

The click library added type annotations in version 8.0.0.  This patch
bumbs the click dependency to that version and removes click from the
list of dependencies that are ignored by mypy.

Enable type checks for click dependency

---

pynitrokey/nk3/device.py

After we send a reboot command to the device, we lose the connection
while it is rebooting.  This causes an error which we want to ignore
because it is expected behavior.  On Linux, the raised error is an
OSError with errno EIO = 5, so we currently check for that.  But on
macOS, an OSError without errno is raised, so we remove the errno check
and ignore all OSError instances.  To make debugging easier, we also add
a log message printing the ignored exception.
<details>
<summary>Example log from macOS</summary>
```
Nitrokey tool for Nitrokey FIDO2, Nitrokey Start, Nitrokey 3 & NetHSM
Traceback (most recent call last):
File "/Users/work/projects/pynitrokey/venv/lib/python3.9/site-packages/fido2/hid/macos.py", line 310, in read_packet
return self.read_queue.get(False)
File …
```

nk3: Fix reboot subcommand for macOS

---

pynitrokey/cli/nk3/__init__.py
pynitrokey/cli/nk3/test.py

This patch adds information about the host system to the log for the nk3
test subcommand.

nk3: Add system information to test log

---

README.md

This patch mentions the Nitrokey 3 in the readme and adds a link to its
documentation on docs.nitrokey.com.

Add Nitrokey 3 support to readme

---

pynitrokey/cli/nk3/__init__.py

This patch removes the -p shorthand for the --pin option for the test
subcommand as it can be confused with the -p/--path option for the nk3
command group.  As --pin already is pretty short, we completely remove
the shorthand instead of changing it.
Fixes #119.

nk3: Remove -p shorthand for --pin option

---

pynitrokey/cli/nk3/__init__.py
pynitrokey/nk3/__init__.py
pynitrokey/nk3/device.py

This patch changes the device lookup logic for the nk3 command group so
that it does not connect to other devices if the --path option is set.
This makes it possible to use multiple devices in parallel.
Closes #122.

nk3: Don’t connect to other devices if --path is set

---

ci-requirements.txt
mypy.ini
pyproject.toml

Both [`mboot`](https://github.com/molejar/pyMBoot) and [`spsdk`](https://github.com/NXPmicro/spsdk), the potential libraries for bootloader interaction, depend on `click` 7 so we have to revert this change that bumped `click` to v8.0.0.  This is especially annoying as we only want to use the library features of the dependencies, but as far as I see we cannot opt out of the CLI as of now.
Reverts Nitrokey/pynitrokey#112

Revert "Enable type checks for click dependency"

---

ci-requirements.txt
mypy.ini
pynitrokey/nk3/__init__.py
pynitrokey/nk3/bootloader.py
pynitrokey/stubs/spsdk/__init__.py
pynitrokey/stubs/spsdk/mboot/__init__.pyi
pynitrokey/stubs/spsdk/mboot/interfaces.pyi
pynitrokey/stubs/spsdk/mboot/properties.pyi
pynitrokey/stubs/spsdk/utils/__init__.pyi
pynitrokey/stubs/spsdk/utils/usbfilter.pyi
pyproject.toml

This patch adds support for listing Nitrokey 3 bootloaders, querying
their UUID and rebooting them.  It uses NXP’s spsdk library to interact
with the bootloader.
----
Still a draft because it depends on #131, otherwise ready to review.  Next step would be implementing the `update` command itself.

nk3: Add support for bootloader using spsdk

---

pynitrokey/cli/nk3/__init__.py

This patch requires the --experimental switch to execute the nk3 update
command on Windows.

nk3 update: Add experimental switch

---

pynitrokey/cli/nk3/__init__.py
pynitrokey/nk3/bootloader.py
pynitrokey/stubs/spsdk/mboot/__init__.pyi

This patch adds the bootloader error code and message to the output if
the firmware update fails.  Previously we only printed a generic “update
failed” error message.

nk3: Show bootloader error if firmware update fails

---

pynitrokey/cli/nk3/__init__.py

This patch adds the --bootloader option to the reboot command that makes
it possible to boot from firmware into bootloader mode.  While users
typically won’t need this command, it can be useful for debugging and
testing.

nk3: Add --bootloader option to reboot command

---

pynitrokey/updates.py

In Python 3.6, re.Pattern is not a valid type and has to be replaced
with typing.Pattern:
https://github.com/python/typeshed/issues/3447
Fixes https://github.com/Nitrokey/pynitrokey/issues/157

Fix type annotation for re.Pattern

---

ci-requirements.txt
pyproject.toml

spsdk specifies cryptography >= 3.3 as their dependency but actually
requires 3.4, see https://github.com/NXPmicro/spsdk/issues/28
With this patch, we increase the minimum version in our own dependency
list to work around this issue.

Bump cryptography dependency to >= 3.4

---

.gitlab-ci.yml
ci-requirements.txt
pyproject.toml

This patch syncs the contents of the dependency lists in
ci-requirements.txt and in pyproject.toml.  Hopefully, this fixes an
issue with missing dependencies on Windows:
https://github.com/Nitrokey/pynitrokey/issues/164

Sync dependency lists

---

pyproject.toml

flit 3.2 added support for build metadata in the format specified by PEP
621 [0] (called “new-style metadata” in flit, see [1]).  This patch
updates the pyproject.toml file to use this new standard format.
[0] https://www.python.org/dev/peps/pep-0621/
[1] https://flit.readthedocs.io/en/latest/pyproject_toml.html
This is also extracted from #121 to keep compatibility with older pip versions.  (As flit is only required for developers and maintainers, increasing the flit minimum version should not cause any issues.)  Using the standardized metadata format is future-proof and more flexible with regard to the choice of build tools.

 Migrate to flit >=3.2 with PEP 621 metadata

---

pynitrokey/cli/nk3/__init__.py
pynitrokey/stubs/spsdk/mboot/exceptions.pyi

Users report issues with the bootloader connection after the reboot.
Apparently, the udev rules are not yet applied when we try to connect to
the device.  We mitigate this issue by performing up to three retries.
This also adds a reference to the udev rules to the error message if
nitropy is running on Linux.
Fixes https://github.com/Nitrokey/pynitrokey/issues/167

nk3 update: Handle bootloader connection issues

---

pynitrokey/cli/nk3/__init__.py
pynitrokey/nk3/device.py
pynitrokey/nk3/exceptions.py

This patch improves the error message shown if the user does not confirm
a reboot operation with a touch button press.
Fixes https://github.com/Nitrokey/pynitrokey/issues/173

nk3: Improve error message for missing confirmation

---

pynitrokey/cli/nk3/__init__.py

As pointed out by mstarecek in [0], the lpc55 reports the correct error
code even without checking the abort frames, so there is no need to
re-run the firmware update for better diagnostics and we can remove the
corresponding TODO.
[0] https://github.com/NXPmicro/spsdk/issues/29#issuecomment-1031353319

Remove outdated todo regarding firmware update

---

pynitrokey/cli/__init__.py

For all devices, we are currently using list as the name for the
subcommand that lists the devices.  Only on the top level, we use ls
instead.  This patch makes the CLI more consistent by renaming the
top-level ls command to list and adding an alias with a deprecation
warning for the old name.

Rename ls command to list

---

pynitrokey/cli/exceptions.py
pynitrokey/cli/nk3/__init__.py

Currently, the local_critical function defined in pynitrokey.helpers is
the preferred way to report a critical error.  Per default, it prints a
support message mentioning the log file location and terminates the
program.  The problem with this approach is that it is not clear from
the API that the function call terminates the program.  This affects
static analysis and code readability.
This patch introduces the CliException, a subclass of
click.ClickException.  Raising this exception from a click command has
the same effect as calling the local_critical function while making it
clear that the regular program flow is disrupted.
Fixes https://github.com/Nitrokey/pynitrokey/issues/135
----
What do you think of this approach?  A possible improvement would be to use `local_critical` for all …

cli: Add CliException for easier error handling

---

pynitrokey/helpers.py

Previously, we renamed the nitropy ls command to list.  With this patch,
we also update the local_critical helper method to use this new name so
that we don’t cause a deprecation warning.

Use list instead of ls in local_critical

---

pynitrokey/cli/update.py
pynitrokey/helpers.py

Correct Nitrokey FIDO2 update
- Check available firmware before downloading
- Require --force switch if current firmware is up-to-date
- Visual reformat of the messages
- Correct reconnection after the bootloader switch
- Use the new list command
Tested on Fedora 34, with market version of Nitrokey FIDO2.

Correct Nitrokey FIDO2 update

---

pynitrokey/cli/nk3/__init__.py
pynitrokey/updates.py

This patch makes the error message that is shown if the firmware file
already exists less intimidating by introducing a custom exception and
disabling the support hint.
Fixes https://github.com/Nitrokey/pynitrokey/issues/189
----
Now instead of this:
```
Nitrokey tool for Nitrokey FIDO2, Nitrokey Start, Nitrokey 3 & NetHSM
Failed to download firmware update v1.0.1
Exception encountered: Exception('File ./firmware-nk3xn-lpc55-v1.0.1.sb2 already exists and may not be overwritten')
/home/jens/.local/lib/python3.10/site-packages/pynitrokey/cli/__init__.py:90: UserWarning: The ls command is deprecated. Please use list instead.
warnings.warn("The ls command is deprecated. Please use list instead.")
-------------------------------------------------------------------------------- …
```

nk3: Improve error message for fetch-update

---

pyproject.toml

As discussed in <https://github.com/NXPmicro/spsdk/issues/34>, spsdk only aims to be compatible between patch releases so we add a corresponding maximum version to the dependency specification.

Add maximum version for spsdk dependency

---

pynitrokey/cli/start.py
pynitrokey/start/usb_strings.py

- Add `start rng` command for getting random data from Nitrokey Start.
- Update `list` command to print all USB strings.

Nitrokey Start: update list and add get random data command

---

wine-build/nitropy.spec.tmpl

Fixes https://github.com/Nitrokey/pynitrokey/issues/170
This is reported to fix the `nitropy.exe`.  @daringer Can you please test it on your system and also check whether the installer works?

Add libusbsio DLLs to Windows build script

---

README.md
docs/developer-guide.rst

This patch adds a developer guide for the pynitrokey project, mainly to
document our decision on password handling as discussed here:
https://github.com/Nitrokey/pynitrokey/pull/199#discussion_r806160559

Add pynitrokey developer guide

---

pynitrokey/cli/start.py

Add default value for the list's "--verbose" optional parameter
Fixes https://github.com/Nitrokey/pynitrokey/issues/205

Add default value for the list's "--verbose" optional parameter

---

pynitrokey/cli/nk3/test.py
pynitrokey/nk3/utils.py

With this patch, we extend the FIDO2 cert checks for the nk3 test
subcommand:
- Instead of a fixed value, we allow multiple values for different
firmware versions.
- Instead of only printing a note if the values don’t match, we now fail
the test instead.
In the future, we could add a --development flag that replaces the
certificate list with the development certificates.

nk3 test: extend FIDO2 cert checks

---

.github/pull_request_template.md

Add initial PR template
Let's review it quickly (to introduce it asap; deadline today) and change it later as we go.
Connected:
- https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates
Fixes #217

Add initial PR template

---

pyproject.toml

cryptography 37 drops Python 3.6 support and does not work with spsdk,
so we add it as an upper bound to the version requirement.
Fixes https://github.com/Nitrokey/pynitrokey/issues/223

Require cryptography < 37

---

pynitrokey/cli/nethsm.py
pynitrokey/cli/nk3/__init__.py
pynitrokey/cli/storage.py
pynitrokey/helpers.py

This patch changes prompts from click.confirm, click.prompt or
pynitrokey.helpers.AskUser to be printed to stderr instead of stdout.
This makes sure that the user will see the prompt even if the output is
redirected to a file or piped to another process.  This patch does not
fix this issue for options with prompt=True as that is more complex.
Fixes #228
----
Regarding options with `prompt=True`, I see the following options:
- subclass `click.Option` and override the `prompt` function to use `err=True`
- wrap `click.option` and set `default` to a custom prompt function if `prompt=True`

Redirect prompts to stderr

---

pyproject.toml

We already changed the code to use fido2 1.0 in #234.  This patch
updates the dependency version in pyproject.toml to reflect this change.
It also adds an upper bound for the version to avoid pulling in
incompatible versions.

Bump fido2 dependency

---

.github/pull_request_template.md
Makefile
build-wine.sh
pyproject.toml
wine-build/Dockerfile
wine-build/build-wine-docker.sh

This PR bumps the minimum version for py to 3.9 and fixes the wine build
- bump change `pyproject.toml` to require python 3.9
- update `Dockerfile` and build script for the wine build creating the windows `.exe` 
- remove `.msi` build for now
- OS: Arch Linux / Windows VM
- device's model: -
- device's firmware version: -

bumps the minimum version for py to 3.9 and fixes the wine build

---

wine-build/build-wine-docker.sh

This PR fixes the CI build of the Windows binary.
- Replace hardcoded version in the binary name with a glob
Related #237

Remove hardcoded version in the name of the final binary

---

README.md

This patch removes the documentation from the readme and refers users to
docs.nitrokey.com instead.  We only keep the instructions for manual
identity switching for the Nitrokey Start as it is not yet available on
docs.nitrokey.com.

Refer to documentation on docs.nitrokey.com

---

README.md

The Current State section was outdated and would be redundant to the
user documentation if we would expand it, so we remove it.

Remove Current State section from readme

---

pyproject.toml

This patch bumps the nrfutil dependency to version 6.1.4 which is now
compatible with Python 3.10.  It also has a fixed protobuf dependency
specification so that we no longer need it in our dependency list.
- Update nrfutil dependency to v6.1.4.
- Remove the explicit protobuf dependency.
- OS: Debian stable
- device's model: -
- device's firmware version: -
@daringer Can you please check with Python 3.10?

Bump nrfutil dependency to 6.1.4

---

pynitrokey/cli/pro.py
pynitrokey/cli/storage.py
pynitrokey/libnk.py

This patch adds support for changing the firmware update password on the
Nitrokey Pro and Nitrokey Storage.  Note that we consistently use the
term “firmware password” for both devices.
Fixes: https://github.com/Nitrokey/pynitrokey/issues/97
@szszszsz I could not test the command for the NK Pro because all my Pros have firmware versions older than 0.11.
- Add `change_firmware_password` methods to `NitrokeyPro` and `NitrokeyStorage` in `pynitrokey.libnk`
- Add `change-firmware-password` subcommands to `pro` and `storage` commands
- OS: Debian Stable
- device's model: NK Pro, NK Storage
- device's firmware version: 0.10, 0.53

pro, storage: Support changing firmware password

---

pynitrokey/cli/fido2.py
pynitrokey/stubs/fido2/cbor.pyi
pyproject.toml

As discussed in [0] and [1], the cbor dependency is unmaintained and
should be replaced.  But it is actually only used in one command that is
not even active, and fido2.cbor provides a simple cbor implementation
that is sufficient for our needs.  So with this patch, we change the
(unused) fido2 probe subcommand to use fido2.cbor instead of cbor and
drop the cbor dependency.
Fixes: https://github.com/Nitrokey/pynitrokey/issues/93
[0] https://github.com/Nitrokey/pynitrokey/issues/93
[1] https://github.com/Nitrokey/pynitrokey/commit/bc45e74d377f28853ff05cfe926e5ac9b7b36267
- Replaces `cbor` with `fido2.cbor`
- device's model: -
- device's firmware version: -

Drop cbor dependency

---

pynitrokey/cli/nk3/test.py

This patch adds the hash of the FIDO2 attestation certificate used on
the NK3AM/nrf52 to the list of allowed hashes for the nk3 test
subcommand.
- Update FIDO2 cert hashes.
- device's firmware version: v1.1.0

nk3 test: Add FIDO2 cert hash for NK3AM/nrf52

---

pynitrokey/cli/nk3/__init__.py
pynitrokey/cli/storage.py
pynitrokey/stubs/fido2/ctap.pyi
pyproject.toml

According to mypy, the subset of spsdk that we use in this crate did not
change with the 1.7.0 release so we can update the version requirement in
pyproject.toml to spsdk 1.7.0.  This also allows us to bump the click and black
dependencies.
- Update spsdk version requirement to 1.7.0, click to 8.0.0 and black to 22.1.0.
- device's model: -
- device's firmware version: -

Support spsdk 1.7.0

---

pynitrokey/cli/nk3/__init__.py
pynitrokey/cli/nk3/test.py
pynitrokey/nk3/device.py
pynitrokey/stubs/smartcard/Card.pyi
pynitrokey/stubs/smartcard/CardConnection.pyi
pynitrokey/stubs/smartcard/Exceptions.pyi
pynitrokey/stubs/smartcard/System.pyi
pynitrokey/stubs/smartcard/__init__.pyi
pyproject.toml

This PR adds two tests to the `nk3 test` subcommand to make sure that the bootloader is locked and the firmware does not contain the provisioner application.  As the first check currently only works with lpc55 devices, it also adds a `--lpc55` flag to enable it.
To fix the CI, we have to install `swig` so that `pyscard` can be built.
- device's model: Nitrokey 3 CN, AM
- device's firmware version: v1.2.0
```
[3/5]   Bootloader configuration        SUCCESS  
[4/5]   Firmware mode                   SUCCESS
```
vs.
```
[3/5]   Bootloader configuration        FAILURE         bootloader not locked
[4/5]   Firmware mode                   FAILURE         provisioner application active
```

nk3 test: Add tests for bootloader configuration and firmware mode

---

pynitrokey/cli/nk3/__init__.py
pynitrokey/cli/nk3/test.py

This PR makes it possible to easily and reliably select the tests to execute.
- Add `--only`, `--all`, `--include`, `--exclude` options to select the test cases.
- Add `--list` option to list the selected test cases.
- Remove `--lpc55` option (use `--include bootloader` instead).

nk3 test: Improve test selection

---

pynitrokey/cli/nk3/test.py
pyproject.toml

3b8538f601b1ac7def4d6cbc658b47a91e2c8f6b introduced the pyscard dependency for implementing the firmware mode test.  Yet this dependency has some additional build dependencies and no binary wheel for Linux. As the firmware mode test is mostly relevant for production and not for end users, we make the pyscard dependency and the firmware mode test otional and put it behind the pcsc extra.
Fixes https://github.com/Nitrokey/pynitrokey/issues/273

Make pyscard optional

---

pynitrokey/cli/__init__.py

This patch enforces UTF-8 encoding for the log file to avoid issues like in https://github.com/Nitrokey/pynitrokey/issues/272 where log calls cause encoding errors.

cli: Force UTF-8 encoding for log file

---

pynitrokey/cli/fido2.py
pynitrokey/cli/nk3/__init__.py
pynitrokey/helpers.py

This patch adds a warning to the fido2 and nk3 subcommands that is triggered if the operating system is Windows and the user is not an admin.
Untested because I don’t have access to a Windows machine.
Fixes https://github.com/Nitrokey/pynitrokey/issues/272

fido2, nk3: Warn if Windows user is not admin

---

pynitrokey/cli/nethsm.py

This PR adds user confirmation requests to the NetHSM `factory-reset`, `reboot`, and `shutdown` commands.
*No major technical changes*
- OS: Fedora Linux 36
Change adds a `Do you want to continue? [y/N]:` request to the above mentioned commands.
Fixes #267

Nethsm confirmation prompt

---

pynitrokey/cli/nk3/__init__.py
pynitrokey/conftest.py
pynitrokey/nk3/device.py
pynitrokey/nk3/otp_app.py
pynitrokey/test_otp.py
pyproject.toml

This PR adds support for Oath Authenticator app over CTAPHID interface. See below for details:
- https://github.com/Nitrokey/oath-authenticator/releases/tag/0.2.0
- Add Oath Authenticator app support over CTAPHID
- Add tests for it
- Add CLI interface through `nk3 otp` subcommands
- OS: Fedora 35
- device's model: USB/IP simulation
- device's firmware version: https://github.com/Nitrokey/nitrokey-webcrypt-usbip/commit/e0859b97c531ce3207114aa4a9a7da1df84abc20
```text
$ nitropy nk3 otp
Command line tool to interact with Nitrokey devices 0.4.30
Usage: nitropy nk3 otp [OPTIONS] COMMAND [ARGS]...
Manage OTP secrets on the device.
Options:
--help  Show this message and exit.
Commands:
get       Generate OTP code from registered credential.
register  Register OTP credential.
remove    Remove OTP …
```

Add Oath Authenticator support over CTAPHID

---

pynitrokey/start/upgrade_by_passwd.py

Nitrokey Start update process corrections, which remove some confusing behavior.
This PR improves update process by:
- not passing further empty Admin PIN for the update, which ends up in a confusing error - instead asks to use default value, and asks again otherwise
- restarting the smart card services stopped during the update process, so user would not end up confused due to device not being reachable by GnuPG
- OS: Linux Fedora 35
- device's model: Nitrokey Start 
- device's firmware version: RTM 12.1

Nitrokey Start update process corrections

---

pynitrokey/cli/nk3/__init__.py
pynitrokey/conftest.py
pynitrokey/nk3/otp_app.py
pynitrokey/test_otp.py

This PR introduces authentication handling, extends tests and supports fuzzing.
- Handle authentication commands in CLI and library
- Load/capacity tests
- Authentication tests
- Invalid data tests
- Save outgoing data for fuzzing
- OS: Linux Fedora 35
- device's model: USB/IP simulation, Nitrokey 3 CN
- device's firmware version: 1.2.2 alpha
```
sz@stumpy ~/w/solo-python (load-tests)> ./venv/bin/nitropy nk3 otp
Command line tool to interact with Nitrokey devices 0.4.30
Usage: nitropy nk3 otp [OPTIONS] COMMAND [ARGS]...
Manage OTP secrets on the device.
Options:
--help  Show this message and exit.
Commands:
clear-password  Clear the passphrase used to authenticate to other...
get             Generate OTP code from registered credential.
register        Register OTP credential.
remove …
```

Authentication, load tests and fuzzing support

---

pynitrokey/cli/fido2.py
pynitrokey/fido2/client.py

This PR adds fido2 sub-commands to list all and delete specific resident keys from Nitrokeys.
- Added list-credentials command which outputs all stored credentials into terminal, as well as the remaining space for more creds.
- Added delete-credential command which takes a hex encoded credential id and tries to delete it from the key.
- Added structure for update-credential command which is not yet working but with a little fixing can be used to update user information for a given key.
- [?] added labels
- OS: Pop!_OS 22.04 LTS
- device's model: Nitrokey 3 mini
- device's firmware version: v1.1.0
list-credentials command output example
delete-credential command output example
Fixes #

Added list-credentials and delete-credential command

---

pynitrokey/cli/nk3/__init__.py
pynitrokey/nk3/device.py
pynitrokey/nk3/provisioner_app.py

This patch adds a hidden subcommand for the provisioner app to the nk3
command.  Currently, it only supports provisioning the FIDO2 attestation
certificate and key.  Besides importing the key and certificate, it also
performs some validation steps to ensure that the key and certificate
match and that the certificate meets the specified requirements.
- Add `ProvisionerApp` class.
- Add hidden `provision` subcommand to `nk3`.

nk3: Support provisioner app

---

pynitrokey/cli/nk3/__init__.py
pynitrokey/cli/nk3/test.py

- Always show the NK3 UUID with 32 characters for consistency.

nk3: Show leading zeros for UUID

---

pynitrokey/cli/nk3/__init__.py
pynitrokey/cli/nk3/test.py
pynitrokey/nk3/base.py
pynitrokey/nk3/bootloader/lpc55.py
pynitrokey/nk3/bootloader/nrf52.py
pynitrokey/nk3/device.py
pynitrokey/nk3/utils.py

- Add `Uuid` class for consistent formatting of UUIDs.

nk3: Add Uuid class

---

pynitrokey/cli/nk3/update.py
pynitrokey/nk3/updates.py

This patch refactors the Nitokey 3 firmware update code so that it is
possible to use it in other contexts, namely the Nitrokey App 2.
Notes:
- I was only able to test the execution path using the downloaded firmware file.  Please test the standard update including the download too.
- My first test of this code caused an incomplete firmware update, so I head to break the device casing to access the BL button.  I was not able to reproduce this so I assume it was a fluke, but please test extensively and preferably only on development devices.
cc @Niklap97
- Make firmware update implementation reusable.
- OS: Debian stable
- device's firmware version: v1.0.4-rc.3

nk3: Make firmware update implementation reusable

---

pynitrokey/nk3/device.py

This PR adds a modification of the path from str to bytes for Windows systems.
- added an if-statement to the device open-function that causes the path to be converted to bytes (utf-8) on Windows systems.
- OS: Windows 11 Pro (22H2)
- device's model: NK3C NFC
- device's firmware version: v1.2.2
```
No CTAPHID device at path \\?\hid#vid_20a0&pid_42b2&mi_01#9&eacc9e6&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}
Traceback (most recent call last):
File "c:\Users\..\nitrokey-app2\venv\lib\site-packages\pynitrokey\nk3\device.py", line 139, in open
device = open_device(path)
File "c:\Users\..\nitrokey-app2\venv\lib\site-packages\fido2\hid\__init__.py", line 266, in open_device
descriptor = get_descriptor(path)
File "c:\Users\..\nitrokey-app2\venv\lib\site-packages\fido2\hid\windows.py", line …
```

Convert path to bytes for Windows systems

---

Makefile
pynitrokey/cli/nk3/test.py
pynitrokey/conftest.py
pynitrokey/fido2/client.py
pynitrokey/nk3/bootloader/__init__.py
pynitrokey/nk3/bootloader/nrf52.py
pynitrokey/nk3/otp_app.py
pynitrokey/nk3/utils.py
pynitrokey/updates.py

This PR updates the `isort` python version used to 3.9 and applies it.

update isort to python version 3.9

---

Makefile
pynitrokey/cli/nk3/test.py
pynitrokey/conftest.py
pynitrokey/fido2/client.py
pynitrokey/nk3/bootloader/__init__.py
pynitrokey/nk3/bootloader/nrf52.py
pynitrokey/nk3/otp_app.py
pynitrokey/nk3/utils.py
pynitrokey/updates.py

This PR updates the rules to use Python 3.9. The "35" used until now is not available in the latest black/isort releases, thus fail on the new setups.
- update black to 39
- update isort to 39

Make fix reformats, with Python set to 39

---

pyproject.toml

This PR enforces python 3.9 for mypy checks during `make check`
- OS: Arch
- device's model: n/a
- device's firmware version: n/a

Enforce python 3.9 for mypy

---

pynitrokey/nk3/utils.py

This PR adds a conversion for int to the nk3 uuid class
- Adds a `__int__` method to `Uuid` class of nk3 utils.
- OS: Fedora 37
Fixes #

Add int return for nk3 device uuid

---

Makefile
pynitrokey/nk3/otp_app.py
pynitrokey/test_otp.py

This PR corrects lint errors, introduced with the recent merge.
The change scope is limited to `otp_app` and `test_otp`.
- specify variable types
- do not reuse names

Mypy lint corrections for otp_app

---

pynitrokey/cli/nk3/__init__.py

This PR adds simple prompt to all OTP commands, asking user to touch the device if it blinks
```
sz@stumpy ~/w/solo-python (otp-ask-for-touch)> ./venv/bin/nitropy nk3 otp get aa --experimental
Command line tool to interact with Nitrokey devices 0.4.33
Please touch the device if it blinks
Timestamp: 2023-02-27T13:21:13 (1677500473), period: 30
615483
sz@stumpy ~/w/solo-python (otp-ask-for-touch)> ./venv/bin/nitropy nk3 otp register aaaa4 AAAAAAAA --kind HOTP --experimental
Command line tool to interact with Nitrokey devices 0.4.33
Please touch the device if it blinks
sz@stumpy ~/w/solo-python (otp-ask-for-touch)>
```
Fixes #325

Ask user to touch the device when needed on all OTP operations

---

pynitrokey/cli/nk3/__init__.py

This PR removes the requirement for specifying the `--experimental` switch for all of the OTP commands.
To be merged once the OTP/secrets app is released.

Remove requirement for the --experimental switch

---

pynitrokey/cli/nk3/__init__.py
pynitrokey/cli/nk3/secrets.py
pynitrokey/conftest.py
pynitrokey/nk3/otp_app.py
pynitrokey/nk3/secrets_app.py
pynitrokey/test_secrets_app.py

This PR renames the Secrets App, previously known as OTP, and extracts the CLI interface to a separate module for easier maintenance.
- extract CLI interface out of __init__.py
- rename OTP -> SecretsApp
- rename CLI: otp -> secrets
- rename CLI: otp/show -> secrets/list
- rename CLI: otp/set-password -> secrets/set-pin
- rename CLI: NITROPY_OTP_PASSWORD -> NITROPY_SECRETS_PASSWORD
- update tests with the new name
- correct showing version info on the status command
- no other changes in features or bugfixes
```
sz@stumpy ~/w/solo-python (otp-quickfixes)> ./venv/bin/nitropy nk3 secrets
Command line tool to interact with Nitrokey devices 0.4.33
Usage: nitropy nk3 secrets [OPTIONS] COMMAND [ARGS]...
Nitrokey Secrets App. Manage OTP secrets on the device. Use
NITROPY_SECRETS_PASSWORD to pass …
```

Refactor Secrets Application interface

---

Makefile
pynitrokey/cli/nk3/__init__.py
pynitrokey/cli/nk3/test.py
pynitrokey/nk3/admin_app.py
pynitrokey/nk3/device.py
pynitrokey/nk3/updates.py
pynitrokey/nk3/utils.py

This patch adds support for two changes in the admin app that will be introduced in version 1.3.0 of the Nitrokey 3 firmware.
- The version subcommand now displays the full version string including the pre-release version.
- A new status subcommand displays the UUID, the firmware version, and the data returned by the new status command:  the init status and the free blocks on the internal and external filesystem.
- device's firmware version: development build
```
$ nitropy nk3 version
Command line tool to interact with Nitrokey devices 0.4.33
v1.2.2-alpha.20230224
$ nitropy nk3 status
Command line tool to interact with Nitrokey devices 0.4.33
UUID:               223FE5E2AE287150AD9DAD9E34B7F989
Firmware version:   v1.2.2-alpha.20230224
Init status: …
```

nk3: Add support for extended version and status

---

pynitrokey/cli/nk3/__init__.py
pynitrokey/nk3/bootloader/__init__.py
pynitrokey/nk3/bootloader/lpc55.py
pynitrokey/nk3/bootloader/nrf52.py
pynitrokey/nk3/updates.py

This PR contains two improvements when providing firmware images directly:
- Support both `alpha` and `firmware` prefixes (previously: only `firmware`)
- Extract full version from filename
- device's firmware version: v1.2.2-alpha.20230224
```
$ nitropy nk3 update /tmp/alpha-nk3xn-lpc55-v1.2.2-alpha.20221130.sb2                                                                                                        
Command line tool to interact with Nitrokey devices 0.4.33                                               
Current firmware version:  v1.2.2-alpha.20230224                                                         
Updated firmware version:  v1.2.2-alpha.20221130                                                         
Please do not remove …
```

nk3 update: Improve filename parsing

---

pynitrokey/nk3/utils.py

This PR adds `__hash__` to `nk3.utils.Version` so it can be used as e.g., dict-index
- OS: Arch
- device's model: nk3am/nk3an
- device's firmware version: 1.3.0

nk3: impl __hash__ for Version dataclass

---

Makefile
pynitrokey/conftest.py
pynitrokey/nk3/secrets_app.py
pynitrokey/test_secrets_app.py
pyproject.toml

This PR adds timestamp to logged lines, and a run helper for fast test execution.
- add timestamps to log
- use log instead of prints
- add helper calls through Makefile
- allow to finish earlier load tests (after 100 credentials, and 1000 - requires running `slow` mark)
- do not log responses doubly when it consist only of a single packet
- OS: Linux Fedora
- device's model: Nitrokey 3
- device's firmware version: `hw-key / v1.2.2-alpha.20230224-36-g9893945`

Secrets App test and logging improvements

---

pynitrokey/cli/nk3/secrets.py

This PR corrects problems spotted at [#332 ](https://github.com/Nitrokey/pynitrokey/pull/332#issuecomment-1469858353)
- do not use snake case for some arguments
- print provided timestamp, instead of using the current time

CLI: correct args names, and show proper timestamp value

---

pynitrokey/nk3/updates.py

This PR increases the default timeout for the finalization step after the update by the factor of 2 to 30secs. 
- OS: Arch
- device's model: nk3am
- device's firmware version: 1.3 alpha 20230320

nk3: increase default finalization timeout to 30secs

---

pynitrokey/cli/nk3/test.py
pynitrokey/nk3/utils.py

Due to the issues discussed in #339 [0] and #340 [1], this patch removes the `Version.__hash__` method and replaces the only usage of Version in a dict with a flattened list.
[0] https://github.com/Nitrokey/pynitrokey/pull/339
[1] https://github.com/Nitrokey/pynitrokey/pull/340
Fixes: https://github.com/Nitrokey/pynitrokey/issues/349

nk3: Drop Version.__hash__

---

pynitrokey/cli/nk3/__init__.py
pynitrokey/cli/nk3/update.py
pynitrokey/nk3/updates.py

This patch adds an option to the nk3 update subcommand to select the version to update to.  This removes the need to manually download the firmware images for alphas and release candidates.
Fixes: https://github.com/Nitrokey/pynitrokey/issues/257

nk3 update: Add --version option

---

pynitrokey/fido2/client.py

An error with an unexpected error code was previously ignored in `NKFido2Client.cred_mgmt`, leading to an uninitialized variable being used in the following code.  This patch fixes the issue by raising all unhandled errors.
Fixes: https://github.com/Nitrokey/pynitrokey/issues/355

fido2.client: Raise unhandled error in cred_mgmt

---

Makefile

Previously, we did not have an all target in the Makefile.  This means the first target, init-fedora37, was the default target, which does not really make sense.  This patch adds an explicit all target that calls init instead.

Set default make target to init

---

pynitrokey/cli/nk3/test.py

This patch adds the provisioner test to the default excludes for the nitropy nk3 test command.  The reason for this is that it the test is not relevant outside of production and is likely to fail if gnupg/scdaemon is running or if there is an issue with pcscd.
It also changes the test setup so that the provisioner test case is always listed, even if pyscard is not installed.  In this case, it is marked as skipped.
Fixes https://github.com/Nitrokey/pynitrokey/issues/323
- Add provisioner test case to default excludes in `nitropy nk3 test`.
- Always list provisioner test case even if `pyscard` is missing.
- device's firmware version: v1.0.3
```
[5/6]   provisioner     Firmware mode                   SKIPPED         pcsc feature is deactivated
```

nk3 test: Fix provisioner test

---

pynitrokey/cli/nk3/__init__.py
pynitrokey/nk3/admin_app.py

This patch adds the device variant to the output of nk3 status.  This requires firmware v1.3.1-test.20230417 or later.
Fixes: https://github.com/Nitrokey/pynitrokey/issues/344
- Add `Variant` enum and `variant` field for `Status` in `pynitrokey.nk3.admin_app`.
- Add the device variant to the output of `nk3 status`.
- device's firmware version: v1.3.1-test.20230417
```
$ nitropy nk3 status
Command line tool to interact with Nitrokey devices 0.4.36                                               
UUID:               ...
Firmware version:   v1.3.1-test.20230417
Init status:        ok                                                                                   
Free blocks (int):  19 …
```

nk3 status: Add variant

---

Makefile
pynitrokey/cli/nk3/secrets.py
pynitrokey/conftest.py
pynitrokey/nk3/secrets_app.py
pynitrokey/test_secrets_app.py
pyproject.toml

This PR updates Secrets App API and tests for brute force protection and PIN-less access
- Update CLI to ask for PIN when needed (previously: always)
- Update and add new tests
- Handle new Credential attribute 0x04 / PIN-based encryption
- Add and update log calls
- Add pytest-reporter-html1 to dev dependencies
- Add initial configuration for Ruff Python linter
- Mark more tests slow
- Add support for the brute-force protection for HOTP Verification (inactive by default)
- Update test target in the helper
- Introduce two-variant fixture for either PIN-based or PIN-less Credentials encryption
- Update error messages for CLI handling, without using the global Exception handler
- Previously unfinished tests were either removed or done - there is no `xfail` anymore …

Update Secrets App API and tests for brute force protection and PIN-less access

---

pynitrokey/cli/fido2.py

The RP name is optional when enumerating RPs using the credential management command.  Only the id is required.  This patch changes the fido2 list-credentials subcommand to show the id instead of the name if the name is not set.
Fixes: https://github.com/Nitrokey/pynitrokey/issues/352
- device's firmware version: v1.3.0-rc.1

fido2 list-credentials: Handle missing RP name

---

pynitrokey/cli/nk3/secrets.py
pynitrokey/nk3/secrets_app.py
pynitrokey/start/gnuk_token.py
pynitrokey/test_secrets_app.py

This PR adds support for the new Password Safe feature of Secrets App
- Add Password Safe API to Secrets App
- CLI changes: 
- OTP secret is now an optional named argument: `--secret` (was positional)
- Register command now accepts PWS fields
- New command: `get-password` - get the PWS fields from the Credential
- List command now shows the Credential's type
- API change: for OTP Credentials Kind has no longer a default type
- Add tests
- Allow to create APDUs longer than 256 bytes
- Backwards compatibility with the current stable 1.3.1:
- Register command will be rejected with PWS fields, or with the Kind not set
- Get-Credential command will be rejected as unknown one
To discuss:
- OS: Linux …

Secrets App Password Safe support for Nitrokey 3

---

pynitrokey/nk3/secrets_app.py

Handle showing list items for data w/o property byte
- Show property byte only for firmware newer than 4.11.0.
- OS: Linux Fedora 38
- device's model: NK3 AN
- device's firmware version: 1.4.0 / 1.5.0
Fixes #406

Handle showing list items for data w/o property byte

---

pynitrokey/cli/__init__.py
pynitrokey/confconsts.py
pynitrokey/helpers.py

This PR aims to simplify log file interpretation by also writing the cli parameters that where used to
run the program into the log file.
- Write command line parameters into the log file
- OS: Archlinux Linux 6.1.31-1-lts
After executing `nitropy fido2 --help`
The log file now contains a line like the following:
```
513        INFO pynitrokey.cli cli arguments: ['fido2', '--help']
```
The representation as a list of parameters is done on purpose to make it easier to see how the
Arguments got parsed. (i.e. `nitropy parameter1 "parameter2 with spaces"`) would be represented as
`['parameter1', 'parameter2 with spaces']`
Fixes #309

Log cli parameters

---

pynitrokey/cli/fido2.py
pynitrokey/fido2/__init__.py
pynitrokey/fido2/client.py
pynitrokey/fido2/commands.py
pynitrokey/fido2/dfu.py
pynitrokey/fido2/operations.py
pynitrokey/helpers.py
pyproject.toml

This PR adds type hints for `fido2` and its needed components like `helpers` and `cli.fido2`
* set `fido2` and `cli.fido2` to strict checking with `mypy`
* mainly added type-hints 
- OS: Arch
- device's model: NK3AM + NK FIDO2
- device's firmware version: 1.2.2 + 2.4.0
* overall there are some `# type: ignore` (~20x), which are added to avoid changing logic 
* added `@todo` (3 parts need a rewrite, `make_credential` and `find` related) near these parts, as they have to be rewritten for a proper type hint usage
* for "simple" cases some minimal actual code(-logic) changes have been done
* any random-walk-tests would be highly appreciated using either a nk3 or fido2 device

fido2: add typehints

---

pynitrokey/cli/fido2.py
pynitrokey/cli/program.py
pynitrokey/cli/update.py
pynitrokey/fido2/client.py

This PR fixes some minor things within `fido2`. 
* fix `fido2 challenge-response`
* add `has_pin_set` (needed for `nitrokey-app2`)
* rename some symbols still containing `solo`
* remove `disable_solo_bootloader` -> not supported with our devices
- OS: Arch
- device's model: NK3 Mini
- device's firmware version: 1.5

Some smaller `fido2` fixes

---

pynitrokey/libnk.py

This PR allows to change libnitrokey verbosity through the environmental variable `LIBNK_DEV`.
- change libnk verbosity during initialization, if `LIBNK_DEV` is set and validated
- OS: Fedora 38
- device's model: Nitrokey Storage
- device's firmware version: v0.57

Select libnitrokey verbosity level through environmental variable

---

pyproject.toml

This PR limits the version of the *click* to a maximum of `8.1.3`.
The latest version of *click* has a problem with *mypy* type checks, causing them to fail.
The issue is currently unsolved pallets/click#2558.
- Restricts usable *click* version to `>=8.0` and `<=8.1.3`.
- OS:
Fixes #

Pin the click version

---

pyproject.toml

This patch updates mypy to >=1.4,<1.5.  From my observation, this fixes the occasional assertion errors that we got due to a caching problem.

Update mypy to 1.4

---

pynitrokey/cli/pro.py
pynitrokey/cli/start.py
pynitrokey/cli/storage.py
pynitrokey/cli/update.py
pynitrokey/helpers.py

Check for pynitrokey updates before update firmware of pro, storage, start, fido2
This PR adds a version check of the pynitrokey tool, which is executed before every firmware update.
Users will be warned about updates with older pynitrokey versions.
- Call the api.github.com on update commands to check for the latest pynitrokey version
- OS: Archlinux
```
You are using an outdated version (0.4.30) of pynitrokey.
Latest pynitrokey version is 0.4.38
Updating with an outdated version is discouraged.
Do you still want to continue? [y/N]: 
```
Fixes #198

Check pynitrokey version on firmware updates

---

.github/workflows/cd-linux.yaml
.github/workflows/cd-pypi.yaml
.github/workflows/cd-windows.yaml

This PR changes the event triggers of the CD pipelines to respond to `prereleased` and `released`, instead of `published` and `unpublished`. There is an exception for the Pypi pipeline to only get triggered on `released` event. Reason for this is to not push test releases to Pypi, which could end up in a production environment.
- CD pipeline for Windows/Linux is triggered for `prereleased` and `released` events.
- CD pipeline for Pypi is only triggered for `released` event.
- OS:
Fixes #

Change event triggers from un/published to pre/released

---

pynitrokey/cli/nk3/secrets.py
pynitrokey/nk3/secrets_app.py
pynitrokey/test_secrets_app.py

This PR adds support for the credentials update, introduced in https://github.com/Nitrokey/trussed-secrets-app/pull/99.
It's possible now to rename the credential, change its touch button use requirement, and change content of the PWS fields.
Builds on https://github.com/Nitrokey/pynitrokey/pull/424.
- add API handling for credential update
- add CLI handling for credential update
- add tests
- OS: Linux Fedora 38
- device's model: USB/IP Sim of Secrets App
- device's firmware version: `v0.12.0-10-gf0ac5938`, head of `65-update-credential-2`.
```
~/w/pynitrokey (402-update-credential-2|✔) $ ./venv/bin/nitropy nk3 secrets update --help
Command line tool to interact with Nitrokey devices 0.4.39 …
```

Update credential support

---

pynitrokey/nk3/secrets_app.py
pynitrokey/test_secrets_app.py

This PR adds quick corrections to https://github.com/Nitrokey/pynitrokey/pull/425 tests
Takes into account the recently added credential overwrite protection.

Secrets App tests update

---

docs/developer-guide.rst

This PR documents the steps to take to update the NetHSM client
- document NetHSM client update procedure
- Change the makefile so `make nethsm-api.yml` always downloads the newer version
(I don't have PGP signing configured, sorry for that)

doc: document NetHSM client update procedure

---

pynitrokey/cli/nethsm.py
pynitrokey/nethsm/__init__.py

This PR fixes the NetHSM decrypt cli command where the IV was not provided to the function.
- add --iv option on `nethsm decrypt`
Fixes #438

fix: IV parameter for NetHSM decrypt

---

pyproject.toml

updated urllib3 to `>=2.0` `<2.1`
nethsm to be tested @nponsard - can you take a look please ?
- OS: Arch
- device's model: n/a
- device's firmware version: n/a
Fixes #426

update urllib3 to >=2.0,<2.1; 

---

pynitrokey/cli/nk3/secrets.py
pynitrokey/cli/nk3/test.py
pynitrokey/fido2/__init__.py
pynitrokey/fido2/client.py
pynitrokey/fido2/dfu.py
pynitrokey/fido2/operations.py
pynitrokey/nk3/bootloader/__init__.py
pynitrokey/nk3/bootloader/lpc55.py
pynitrokey/nk3/secrets_app.py
pynitrokey/nk3/updates.py
pynitrokey/start/gnuk_token.py
pynitrokey/updates.py
pyproject.toml

Strict mypy checks cannot be enabled on a per-module level, so we used the disallow_untyped_defs option to replace them.  But actually there are many more options that would be set in strict mode.  This patch adds these options to the mypy configuration, fixes some missing or wrong annotations and adds some ignores for more complex issues so that the checks still pass.
Fixes: https://github.com/Nitrokey/pynitrokey/issues/443

Extend strict mypy checks

---

pynitrokey/nethsm/__init__.py

This PR improves the handling of API errors in the nethsm commands.
- OS: Arch
- device's model: NetHSM docker
- device's firmware version: 882a5a3

feat: improve NetHSM API exception handling

---

pynitrokey/nk3/updates.py

This PR fixes the:
```
Exception encountered: RuntimeError("generator didn't stop after throw()")
```
error by introducing a `time.sleep(1)` directly after asking the device to boot into the bootloader so that udev has enough time to properly handle the new device.
- OS: Arch
- device's model: NK3AN
- device's firmware version: 1.5
Fixes #394

Fix "generator didn't stop" update error for LPC55 devices

---

pynitrokey/cli/nk3/test.py

Remove pin prompt from `nk3 test`, if `fido2` is activated and pin is required (set) on the target device.
- OS: Arch
- device's model: nk3am
- device's firmware version: 1.5
```
❯ nitropy nk3 test 
Command line tool to interact with Nitrokey devices 0.4.39
Found 1 Nitrokey 3 device(s):
- Nitrokey 3 at /dev/hidraw12
FIDO2 tests activated: Device requires pin, but not set
```
Fixes #411

nk3 test/fido2: early exit if pin not set - fixes #411

---

pynitrokey/cli/nk3/test.py
pynitrokey/nk3/admin_app.py

This PR adds a test that is introduced in the admin app with https://github.com/Nitrokey/admin-app/pull/5
Note that it takes around 30seconds to complete, it's not crashing.

Add SE050 test

---

pynitrokey/nk3/admin_app.py

This PR adds reporting of SE050 initialization errors as introduced in https://github.com/Nitrokey/nitrokey-3-firmware/pull/335/commits/0bc4cded9162635d86bf0b5541b71869b27c515c.
```
UUID:               DF776FB18D7DFE800000000000000000
Firmware version:   v1.5.0-test.20230704
Init status:        UNKNOWN (0x10)
Free blocks (int):  255
Free blocks (ext):  473
Variant:            NRF52
```
Becomes 
```
UUID:               DF776FB18D7DFE800000000000000000
Firmware version:   v1.5.0-test.20230704
Init status:        SE050_RAND_ERROR (0x10)
Free blocks (int):  255
Free blocks (ext):  473
Variant:            NRF52
```

Add SE050_RAND_ERROR reporting in status

---

pynitrokey/cli/nk3/__init__.py
pynitrokey/nk3/admin_app.py

This PR adds the `nk3 get-config` and `nk3 set-config` subcommands to access the device configuration of a Nitrokey 3.
- device's firmware version: https://github.com/Nitrokey/nitrokey-3-firmware/pull/337 (3f976bcb35716515828cec4683241f21d6792810)
```
$ nitropy nk3 get-config fido.disable_skip_up_timeout                                                                                                                                                                                               
Command line tool to interact with Nitrokey devices 0.4.39 …
```

nk3: Add get-config and set-config subcommands

---

.github/workflows/ci.yaml
pynitrokey/cli/nethsm.py
pyproject.toml

This patch extends the nethsm backup and restore commands to validate the backup file.  It also adds validate-backup and export-backup commands to check the content of a backup file.
Fixes: https://github.com/Nitrokey/pynitrokey/issues/456
Depends on:
- https://github.com/Nitrokey/nethsm-sdk-py/pull/52
- https://github.com/Nitrokey/nethsm-sdk-py/pull/47 (when using `nethsm-sdk-py` as a Git dependency instead of a release)

Add backup validation

---

docs/packaging.rst

This patch adds information on packaging pynitrokey.  The most important information is the possibility to generate shell completion scripts for nitropy.

docs: Add packaging info

---

pynitrokey/cli/nk3/__init__.py

Partially fixes https://github.com/Nitrokey/pynitrokey/issues/460.

nk3: Use click.Path where applicable

---

pynitrokey/cli/fido2.py
pynitrokey/fido2/client.py

This PR cleans up the make-credential command and adds support for setting a resident key and user verification requirement.

fido2 make-credential: Clenaup and add rk and uv options

---

pyproject.toml

This PR removes the *frozendict* dependency which was used in the old NetHSM client implementation is now part of the *nethsm-sdk*.
- Remove `frozendict` from `pyproject.toml`.
- OS:
Fixes #

Remove frozendict dependency

---

pynitrokey/cli/exceptions.py
pynitrokey/cli/fido2.py
pynitrokey/cli/monitor.py
pynitrokey/fido2/client.py
pynitrokey/helpers.py
pynitrokey/nk3/bootloader/lpc55.py
pynitrokey/nk3/secrets_app.py
pyproject.toml

Instead of disabling strict checks per default and only enabling them for new code, this patch enables strict checks per default and disables them for old code.  This makes sure that new code is not accidentally ignored.
This patch also fixes some simple typing issues so that we can drop some exceptions.
This is a preparation for adding type checks for the nethsm module and extending the fido2 module.

Reverse mypy exceptions

---

pynitrokey/cli/nethsm.py
pyproject.toml

This update pulls in multiple relevant changes, mainly:
- The auto-generated client is only loaded if required.  This improves execution times significantly, especially for simple commands.
- Key certificates are now always stored as raw bytes, not as strings, so the get-certificate and set-certificate commands had to be updated.
- Changing the backup and unlock passphrases now requires passing the current passphrase.
- Using enums instead of strings.
- Using stronger types and dataclasses for some methods.
- NetHSM API changes that are not visible in the public Python API.
On my machine, this reduces the execution time for simple commands like version or --help from 0.9 s to 0.3 s.

Update nethsm dependency

---

pynitrokey/cli/nk3/__init__.py
pynitrokey/cli/nk3/secrets.py
pynitrokey/helpers.py
pynitrokey/nk3/admin_app.py
pynitrokey/nk3/device.py

This PR adds support for the full-device factory reset command introduced in https://github.com/Nitrokey/nitrokey-3-firmware/pull/383

Add support for full device factory reset command

---

pynitrokey/cli/nk3/__init__.py

With the upcoming firmware release for the Nitrokey 3, changing some configuration values can have side effects, namely a reset of the opcard application.  We will add new commands with additional information and warnings in the future.  For the time being, this patch adds a warning to the set-config command, indicating that it may cause data loss and should only be used for testing and development.
@sosthene-nitrokey We want to release pynitrokey today for some NetHSM fixes.  I’d like to include something like this even if we don’t have the proper commands for changing specific config values yet.  What do you think?

nk3 set-config: Add warning and confirmation prompt

---

pynitrokey/cli/nk3/__init__.py
pynitrokey/nk3/admin_app.py

This patch refactors the set-config command:
1. It checks whether the config option is supported by the device using the GET_CONFIG command before any other steps are performed.
2. For known keys that trigger a reset, currently only opcard.use_se050_backend, a warning and a confirmation prompt are shown.
3. Unknown keys are rejected unless --force is set, trigger a warning and require a confirmation prompt.
4. It adds a --dry-run option to check the infos and prompts that are printed for a config change.
5. It adds an automatic reboot if required.
Potential improvements:
- The metadata for config values should be put into data structures that can also be used by nitrokey-app2.
- Information on whether a command triggers a reset and requires touch confirmation could be queried from the …

nk3 set-config: Add support for opcard.use_se050_backend

---

pynitrokey/cli/nk3/test.py

Allow the SE050 tests to run with firmware version 1.6.0

Remove firmware version check for SE050 test

---

pynitrokey/nk3/bootloader/lpc55.py
pyproject.toml

This PR updates spsdk to version `>= 2.0 <2.1` - this needed some adaptations as interfaces changed
* `StatusCode` import location updated to `.error_codes`
* `McuBoot` import location updated to `.mcuboot`
* use `UsbDevice` instead of `RawHid`
* use `MbootUSBInterface(device)` to init `McuBoot`
* `CertBlockV1` corrected the naming for "root key table hashes" from `rkht` to `rkth`, applied where needed
- OS: Arch
- device's model: nk3an
- device's firmware version: v1.6
Fixes #486
as a side note: spsdk still uses `oscrypt <1.4` so we are still stuck with the openssl bug it introduces...

Update spsdk to v2.0 and adapt

---

pynitrokey/cli/nk3/__init__.py
pynitrokey/cli/nkpk.py
pynitrokey/cli/trussed/__init__.py
pynitrokey/nk3/__init__.py
pynitrokey/nk3/bootloader.py
pynitrokey/nk3/updates.py
pynitrokey/nkpk.py
pynitrokey/trussed/__init__.py
pynitrokey/trussed/bootloader/__init__.py
pynitrokey/trussed/bootloader/nrf52.py

This PR moves the fetch-update and validate-updates command into the trussed module so that they are also available for NKPK and adds the NKPK signature keys so that they work correctly.

nkpk: Add fetch-update, validate-update commands

---

pynitrokey/fido2/client.py

This PR fixes `fido2 list-credential` ctap2 (+pin protocol v2)  by adding the correct permissions 
- OS: Arch
- device's model: nk3am (pin-protv2 dev device), nk3am v1.6
- device's firmware version: see last line

fido2: add permissions for list-creds with pinV2

---

.github/workflows/cd-linux.yaml

This PR patches the oscrypto package used for the linux binary build in the CI.
Motivation is to avoid #431 at least for this build.
- Introduces an additional step in the CI build
- OS:
Fixes #

Patch oscrypto for linux binary

---

pyproject.toml

This PR raises the required version for **pyinstaller**. With the new version the installation process with Python 3.12 works too. Quick testing of some features didn't show any other incompatibilities with Python 3.12. Hence I also added the respective classifier.
- Update **pyinstaller** to `~= 6.5.0`.
- Add Python 3.12 classifier.
- OS:
Fixes #

Bump pyinstaller version

---

.github/workflows/cd-linux.yaml
.github/workflows/cd-pypi.yaml
.github/workflows/cd-windows.yaml
.github/workflows/ci.yaml

This PR updates the following Github Actions in the CI/CD pipelines.
- `actions/checkout@3` -> `actions/checkout@4`
- `actions/upload-artifact@3` -> `actions/upload-artifact@4`
- `actions/download-artifact@3` -> `actions/download-artifact@4`
- `softprops/action-gh-release@1` -> `softprops/action-gh-release@v2`
- The update brings no change in the use of the pipelines, but the deprecation warnings are gone now.
- OS:
Fixes #

Update Github Action versions in the CI/CD pipelines

---

pynitrokey/cli/__init__.py

Added a short version to call the help, i.e. now the help of a functionality is available by calling `--help` and `-h`. 
- Added help option names in the context settings of the click group added to the `nitropy` command.
- Nothing to update in my point of view, please correct me if I'm wrong. 
- OS: macOS Sonoma 14.3.1
- device's model: Nitrokey 3C NFC
- device's firmware version: `v1.6.0-test.20231218`

Add common short version for help of CLI

---

pynitrokey/cli/nk3/__init__.py

I added the same warning as in `update`, but it appears it is just a string without any User-visible behaviour. Should this be changed to local_print?
- Remove the required `--experimental` flag for the factory-reset commands

factory-reset(-app): remove --experimental flag

---

pynitrokey/trussed/bootloader/lpc55.py

Hi,
This PR fixes an incompatibility with spsdk 2.1 which is shipped in Arch Linux. spsdk recently switched to the python-native Enum library and renamed the `desc` method to `get_description` in the process.
`get_description` is called first and falls back to `desc`.
Feel free to make this change without attribution if you don’t feel comfortable merging it without the checks :)
- OS: Arch Linux
- device's model: Nitrokey 3A NFC
- device's firmware version: 1.6.0
Cheers
Konrad

fix: improve forwards compatibility with spsdk 2.1+

---

pynitrokey/cli/fido2.py

This patch adds a get-info subcommand to the fido2 command that prints the response to a GET_INFO request.
Fixes: https://github.com/Nitrokey/pynitrokey/issues/465
----
Example:
```
$ nitropy fido2 get-info
Command line tool to interact with Nitrokey devices 0.4.47
versions: ['U2F_V2', 'FIDO_2_0', 'FIDO_2_1']
extensions: ['credProtect', 'hmac-secret']
aaguid: 8bc54968-07b1-4d5f-b249-607f5d527da2
options: {'rk': True, 'up': True, 'plat': False, 'credMgmt': True, 'clientPin': True, 'largeBlobs': False, 'pinUvAuthToken': True}
max_msg_size: 3072
pin_uv_protocols: [2, 1]
max_creds_in_list: 10
max_cred_id_length: 255
transports: ['nfc', 'usb']
```

fido2: Add get-info subcommand

---

pynitrokey/cli/nk3/update.py
pynitrokey/nk3/updates.py

This PR adds `pre_bootloader_hint` into the updating ABC. This should allow to hook into the process especially for situations like https://github.com/Nitrokey/nitrokey-app2/pull/254 to improve the update process in e.g. QubesOS
- add `pre_bootloader_hint` as hook during update
- implement noop for `pre_bootloader_hint` for cli-based update process
- OS: Arch
- device's model: nk3am
- device's firmware version: v1.7.1

nk3/update: add pre_bootloader_hint for update process

---

pynitrokey/cli/nethsm.py
pyproject.toml

Depends on:
- https://github.com/Nitrokey/nethsm-sdk-py/pull/110

nethsm: Add support for namespaces

---

.flake8
Makefile
pynitrokey/cli/nkpk.py
pynitrokey/cli/trussed/__init__.py
pynitrokey/cli/trussed/test.py
pynitrokey/trussed/bootloader/__init__.py
pynitrokey/trussed/bootloader/lpc55.py
pynitrokey/trussed/device.py

The flake8 whitelist and blacklist got out of sync during refactoring. This patch updates both lists, fixes the resulting lints and simplifies the flake8 configuration.

Fix flake8 lints

---

pynitrokey/trussed/admin_app.py

This PR adapts the result of `nk3 status` to take into account https://github.com/Nitrokey/nitrokey-3-firmware/pull/522
Add the two new error codes: 
- Config (should already have been there)
- RANDOM
- OS:
Fixes #

And random generator and config failures to init status bytes

---

pynitrokey/cli/nethsm.py
pyproject.toml

This PR adds a check for the NetHSM restore command, to determine if the authentication is required based on the state. Also raises the version for _nethsm-sdk-py_.
Depends on Nitrokey/nethsm-sdk-py#124
- Adds a check for the state of NetHSM, to decided if authentication is required (partial restore) or not (unprovisioned restore).
- Bump version of _nethsm-sdk-py_ to `1.2.1`.
- OS:
Fixes #

Require authentication for partial restore

---

.github/workflows/cd-pypi.yaml

Previously, we only built Linux and Windows binaries for pre-releases. But we also want them to be published on PyPI.

ci: Add support for pre-releases on PyPI

---

.github/workflows/cd-linux.yaml
ci-scripts/linux/pyinstaller/pynitrokey-onedir.spec
ci-scripts/linux/pyinstaller/pynitrokey-onefile.spec
ci-scripts/windows/pyinstaller/pynitrokey-onedir.spec
ci-scripts/windows/pyinstaller/pynitrokey-onefile.spec

After we migrated to the Nitrokey Python SDK, we no longer depend on spsdk so the pyinstaller setup can no longer access its metadata (and does not need it anymore).
Tested locally for Linux, not yet tested for Windows.  Maybe we can adapt the CI scripts to do a test run.
We could release this as 0.5.0-post.1 or 0.5.1.

cd: Fix pyinstaller spec

---

.github/workflows/ci.yaml
pynitrokey/cli/nk3/piv.py

This PR makes the commandline options a bit more consistent and adds help texts.
- Remove build for Windows from CI pipeline.
- Makes commandline options a bit more consistent among all the options for PIV.
- Add help texts for commands and options.
- Makes options `key` and `format` case insensitive.
- OS:
Fixes #

PIV rebase update

---

pynitrokey/cli/nk3/__init__.py
pynitrokey/cli/nk3/piv.py
pynitrokey/nk3/piv_app.py
pynitrokey/tlv.py
pyproject.toml

This PR adds PIV commands under `nitropy nk3 piv`
- [x[ signed commits
If we merge this before PIV is stabilised, this will need to be behind a `--experimental` flag.

Add PIV commands

---

pynitrokey/cli/nk3/__init__.py
pynitrokey/cli/nk3/update.py

This PR introduces an option to the `nk3 update` subcommand that allows the update to be automated. 
- Add option `--confirm` to confirm udpate. 
> [!IMPORTANT]
> The automation is only allowed for *updates* of the firmware. Downgrades or other potential issues that require user interaction are **NOT** included in this option. I.e. the confirmation applies only to the functions `confirm_download` and `confirm_update`. 
> [!NOTE]
> I noticed that the update function for the Nitrokey FIDO2 uses `-y` or `--yes` for a similar flag. However, to stay within the naming convention of the class functions of the `nk3` interface, I decided to name the flag `--confirm`. 
- OS: macOS Sequoia 15.0
- device's …

Add confirm option to allow automated updates on nk3 devices

---

pynitrokey/cli/nk3/__init__.py
pyproject.toml

In `set-config`, get the type of the and metadata for the fields, including information regarding the need for power-cycle and validation of accepted values.
Depends on:
- https://github.com/Nitrokey/nitrokey-sdk-py/pull/44
- OS: Arch
- device's model: NK3AM
- device's firmware version: https://github.com/Nitrokey/nitrokey-3-firmware/pull/539
```
python nitropy.py nk3 set-config piv.disabled False
Command line tool to interact with Nitrokey devices 0.6.0
Unknown config value. Expected Bool, got `False`. Unknown config values can only be set if the --force/-f flag is set.  Aborting.
```
```
python nitropy.py nk3 set-config unknown-value False
Command line tool to interact with …
```

Use config field availability information from the sdk

---

pynitrokey/cli/nk3/piv.py
pynitrokey/nk3/piv_app.py
pyproject.toml

removes the dependency on asn1crypto, replacing it with the `cryptography` package and a custom builder
This is one less dependency. asn1crypto is not very widespread so using cryptography is likely the better solution.
- OS: Arch Linux
- device's firmware version: `1.7.0-test20241022`
Fixes #

Remove asn1crypto

---

pynitrokey/nk3/piv_app.py

This PR fixes the import for the TripleDES cipher from `cryptography` to use the new path, instead of the deprecated one that will be removed in a future releases
- No  user facing change
- OS: Arch
- device's model: NK3AN
- device's firmware version: 1.8.0-rc.1
Fixes https://github.com/Nitrokey/pynitrokey/issues/588

Fix deprecation warning with TripleDES

---

Makefile
pynitrokey/cli/__init__.py
pynitrokey/cli/fido2.py
pynitrokey/cli/nkfido2.py
pynitrokey/cli/trussed/tests.py
pynitrokey/fido2/__init__.py
pynitrokey/fido2/client.py
pynitrokey/fido2/operations.py
pyproject.toml

This PR contains several cleanup and refactoring patches as a first step towards https://github.com/Nitrokey/pynitrokey/issues/595.  It does not change the existing commands (except for removing unused arguments) but:
- removes dead code
- moves commands that only work with the Nitrokey FIDO2 into a separate `nkfido2` module
- changes commands that work with all FIDO2 devices to use the fido2 library directly instead of our custom fido2 module
- fixes an incompatibility with the newest version of the python-fido2 library (the hmac-secret extension needs to be enabled explicitly)
The next steps after this PR would be to change the commands in the `nkfido2` module to reject other FIDO2 devices and potentially to move them to a separate command.

Clean up fido commands

---

pyproject.toml

This patch updates the minimum cryptography dependency version to v43 as required by https://github.com/Nitrokey/pynitrokey/pull/589.  As v44 seems to work well too, we can also bump the upper limit.

Update cryptography dependency

---

pynitrokey/fido2/__init__.py
pynitrokey/fido2/client.py

Previously, we executed all fido2 commands on all FIDO2 devices.  But some only work on the Nitrokey FIDO2.  This patch adds a check that ensures that these device-specific commands only enumerate Nitrokey FIDO2 devices.
Fixes: https://github.com/Nitrokey/pynitrokey/issues/453
Fixes: https://github.com/Nitrokey/pynitrokey/issues/536

fido2: Limit VID/PID for Nitrokey FIDO2 commands

---

pynitrokey/cli/fido2.py

Fixes: https://github.com/Nitrokey/pynitrokey/issues/594

fido2 verify: Add support for Nitrokey Passkey

---

pynitrokey/start/gnuk_token.py

The array class is not subscriptable in Python 3.11 and older, causing a TypeError at runtime.  This patch applies the workaround suggested in https://github.com/python/mypy/issues/13942.

Fix type hints for Python 3.11 and older

---

.github/workflows/ci.yaml

This patch extends the CI to run `nitropy --help` on all supported Python versions to catch installation and basic runtime errors.

Improve CI coverage

---

pyproject.toml

We restrict the hidapi dependency to some specific versions to make sure that the hidraw backend is used, see:
https://github.com/Nitrokey/pynitrokey/pull/602
But the hidapi versions that are now eligible are not providing wheels for Python 3.13 so that they have to be compiled from source.  This is an unnecessary complication for non-Linux platforms.  Therefore this patch only applies the restriction on Linux.  Other platforms can use any 0.14 release.

Only restrict hidapi dependency on Linux

---

pynitrokey/cli/nethsm.py

This patch changes all nethsm commands to read the host from the NETHSM_HOST environment variable if it is not set on the command line. This has two benefits:  It makes it easier to run multiple commands for the same host.  And it fixes the problem that the required --host option on the nethsm command group would make it impossible to run --help for a subcommand without setting --host.
Example output if neither is set:
$ nitropy nethsm lock
Command line tool to interact with Nitrokey devices 0.7.3
Missing NetHSM host: set the --host option or the NETHSM_HOST environment variable

nethsm: Read host from NETHSM_HOST if not set

---

pynitrokey/cli/nethsm.py

This PR adds TPM attestation keys and platform configuration records to the system info output.
Based on Nitrokey/nethsm-sdk-py#128
- Print values of TPM attestation keys and platform configuration records if included by the NetHSM.
- OS:
Fixes #

Add TPM information to system information

---

pyproject.toml

This PR bumps the minimum version of `nethsm-sdk-py` to `1.3.0`.
The change is a left over from #628.
-
- OS:
Fixes #

Bump minimum nethsm sdk version to 1.3.0

---

pynitrokey/cli/fido2.py

This PR fixes a typo in the click command output.

Fix typo in delete_credential documentation string.

---

pynitrokey/cli/nk3/secrets.py
pynitrokey/helpers.py

Adds a helper function, which appends the necessary padding to unpadded otp secrets.
A [similar padding fix](https://github.com/Nitrokey/nitrokey-app2/blob/37f30afb7486aec5131075b1d2e2647701834e4c/nitrokeyapp/secrets_tab/__init__.py#L29)  is already implemented in the nitrokey-app2.
This fixes #374 
before:
```
> ./venv/bin/nitropy nk3 secrets add-otp --kind TOTP --touch-button --hash SHA1 somename JBXXAZJAPFXXKIDEMVRW6ZDFMQQHI3ZAORSWY3BANVST6IBIHIFA
Command line tool to interact with Nitrokey devices 0.8.1
An unhandled exception occurred
Exception encountered: Error('Incorrect padding')
[...]
```
after:
```
> ./venv/bin/nitropy nk3 secrets add-otp --kind TOTP --touch-button --hash SHA1 somename JBXXAZJAPFXXKIDEMVRW6ZDFMQQHI3ZAORSWY3BANVST6IBIHIFA
Command line tool to …
```

fix: append required base32 padding when handling unpadded otp secrets

---

pynitrokey/cli/nk3/secrets.py

While we are at it, this fixes #373 , by allowing lowercase in the base32 secret decoding.
Just setting the [casefold parameter](https://docs.python.org/3/library/base64.html#base64.b32decode) of b32decode is also what [nitropy app 2 does](https://github.com/Nitrokey/nitrokey-app2/blob/main/nitrokeyapp/secrets_tab/__init__.py#L33).
Maybe this type of common functionality between the cli and gui application could be moved into the [sdk](https://github.com/Nitrokey/nitrokey-sdk-py) or a separate (frontend) helper library, to make them behave more consistent?

fix: allow lowercase base32 secrets input

---

pynitrokey/cli/nethsm.py
pyproject.toml

This patch updates the NetHSM SDK and adds a --ca-certs option for the nethsm subcommands.

nethsm: Add --ca-certs option

---

.github/workflows/cd-pypi.yaml

This repository uses master as the default branch, not main.

ci: Fix default branch name for TestPyPI releases

---

pynitrokey/cli/nk3/piv.py

This PR adds a command for PIV to automatically create the certificate mappings for Windows.
Windows Update [KB5014754](https://support.microsoft.com/en-us/topic/kb5014754-certificate-based-authentication-changes-on-windows-domain-controllers-ad2c23b0-15d8-4340-a468-4d4f3b188f16) introduced the requirement for strong mappings between a user logon certificate and the Active Directory user account. Since February 2025 this change is enforced by default. The option to return to a compatibility mode will remain until September 2025. Windows offers six values for this certificate mapping, three of them considered strong mappings.
The new command `get-windows-auth-mapping` automatically creates the three strong mappings, based on the certificate in the key slot `9a`, which is used for user …

Windows certificate mapping for PIV

---

.github/workflows/ci.yaml
Makefile
pynitrokey/helpers.py

helpers.b32padding: avoid adding 8 pads when none needed

---

.github/workflows/cd-linux.yaml
.github/workflows/cd-pypi.yaml
.github/workflows/ci.yaml
README.md
poetry.lock
pynitrokey/cli/fido2.py
pynitrokey/cli/nk3/piv.py
pynitrokey/cli/trussed/tests.py
pyproject.toml

This PR includes the following changes:
- Bump the minimum Python version to 3.10.
- Update the fido2 dependency to v2 (https://github.com/Nitrokey/pynitrokey/issues/660).
- Add support for cryptography v45 (https://github.com/Nitrokey/pynitrokey/issues/661).
- Release v0.9.0.

Update fido2 and release v0.9.0

---

.github/workflows/cd-linux.yaml
pyproject.toml

The cd-linux workflow for the v0.9.0 release failed because the version check was run with sh instead of bash:
https://github.com/Nitrokey/pynitrokey/actions/runs/16215994196/job/45785446801
This PR explicitly selects bash as in cd-pypi.yaml and releases v0.9.1 to so that there is a Linux binary for the latest release.

ci: Use bash for version check and release v0.9.1

---

.github/workflows/cd-windows.yaml

We already use Python 3.10 in the Linux CI so it makes sense to apply the same to the Windows CI. This also fixes a strange CI error when installing the project with poetry.

ci: Pin Python version in Windows CI

---

pynitrokey/cli/nk3/piv.py

This is already done by the device but this allows for a better error message that explains the requirements

PIV: validate PINs to be 6 to 8 numbers

---

.github/workflows/ci.yaml
.gitignore
Makefile
poetry.lock
pyproject.toml

This PR adds minimum versions for all dependency and uses uv to test different resolution strategies in the CI. This makes sure that we don’t forgot to update the minimum version when adding new features.
See also: https://github.com/Nitrokey/nitrokey-sdk-py/pull/80
Fixes: https://github.com/Nitrokey/pynitrokey/issues/160

Add minimum dependency versions and test them in CI

---

pynitrokey/cli/trussed/tests.py

Previously, we always required a PIN to create a FIDO2 credential if a PIN has been set.  In firmware version v1.8.2-rc.1, we added support for the makeCredUvNotRqd option which means that credentials can be created without PIN (user verification).  This patch updates the fido2 test in nk3 test to not require the PIN if the device supports makeCredUvNotRqd.
Fixes: https://github.com/Nitrokey/pynitrokey/issues/678

nk3 test: Support credential creation without PIN
